In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors, Descriptors3D
from rdkit.ML.Descriptors import MoleculeDescriptors
from tqdm import tqdm

In [2]:
calc = MoleculeDescriptors.MolecularDescriptorCalculator([desc[0] for desc in Chem.Descriptors._descList])

def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None 
    return calc.CalcDescriptors(mol)

In [3]:
#2D RDKit train dataset descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Train.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
train_2d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_2d_rdkit.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_RDKit_des.csv',index=False)
print("Shape: ",train_2d_rdkit.shape, '\n')
train_2d_rdkit

Shape:  (5568, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,915,CC[C@H](C)[C@H](NC(=O)[C@@H]1CC(=O)N[C@@H](Cc2...,-7.0,15.738544,15.738544,0.010382,-1.908222,0.047997,24.622047,1773.325,...,0,0,0,0,0,0,0,0,0,0
1,888,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1cccc(Cl)c1)N(C)...,-7.0,15.975705,15.975705,0.027671,-1.943827,0.026511,21.983740,1745.057,...,0,0,0,0,0,0,0,0,0,0
2,593,C/N=C(\NC)NCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C...,-7.0,15.828473,15.828473,0.049834,-1.862294,0.021075,22.464000,1733.267,...,0,0,0,0,0,0,0,0,0,0
3,916,CC[C@H](C)[C@H](NC(=O)[C@@H](NC(=O)[C@@H]1CC(=...,-7.0,15.595105,15.595105,0.004954,-1.811756,0.069603,24.479675,1725.281,...,0,0,0,0,0,0,0,0,0,0
4,900,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O...,-7.0,15.867592,15.867592,0.029192,-1.876686,0.046796,23.089431,1723.309,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.7,12.835172,12.835172,0.168936,-0.728726,0.606745,24.965517,402.539,...,0,0,0,0,0,0,0,0,0,0
5564,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.6,12.673271,12.673271,0.196704,-0.722720,0.611202,25.037037,374.485,...,0,0,0,0,0,0,0,0,0,0
5565,2512,CC(C)C[C@H]1NC(=O)[C@@H](C)NCCCCCCNC(=O)[C@H](...,-5.5,12.572226,12.572226,0.181773,-1.016186,0.465702,27.576923,370.494,...,0,0,0,0,0,0,0,0,0,0
5566,2511,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)[C@@H](C)NCC...,-6.3,12.364448,12.364448,0.112529,-1.084532,0.446971,28.200000,356.467,...,0,0,0,0,0,0,0,0,0,0
5567,2506,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)CNCCCCCCNC1=O,-7.8,12.267673,12.267673,0.095114,-1.068282,0.435628,25.750000,342.440,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#2D RDKit test dataset descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Test.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
test_2d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_2d_rdkit.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_RDKit_des.csv',index=False)
print("Shape: ",test_2d_rdkit.shape, '\n')
test_2d_rdkit

Shape:  (1392, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,908,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-7.00,15.806942,15.806942,0.022547,-1.946094,0.037676,23.507937,1777.744,...,0,0,0,0,0,0,0,0,0,0
1,923,CC[C@H](C)[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](...,-7.00,15.512854,15.512854,0.072929,-1.849230,0.082004,25.902439,1725.281,...,0,0,0,0,0,0,0,0,0,0
2,897,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.00,16.029525,16.029525,0.042154,-1.949385,0.046040,22.827869,1701.218,...,0,0,0,0,0,0,0,0,0,0
3,587,CC(C)C[C@@H]1NC(=O)[C@H](Cc2c[nH]cn2)NC(=O)[C@...,-6.74,15.776936,15.776936,0.046352,-1.865645,0.035370,22.622951,1686.166,...,0,0,0,0,0,0,0,0,0,0
4,921,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.54,15.432735,15.432735,0.040020,-1.845687,0.100132,26.663866,1669.173,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,2481,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccccc...,-4.50,12.958074,12.958074,0.156212,-0.733388,0.586385,24.903226,430.593,...,0,0,0,0,0,0,0,0,0,0
1388,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-4.80,12.958074,12.958074,0.156212,-0.733388,0.586385,24.903226,430.593,...,0,0,0,0,0,0,0,0,0,0
1389,5604,CC(C)CN1CC(=O)N[C@@H](Cc2ccccc2)C(=O)NCCCCC(=O...,-6.38,12.898424,12.898424,0.143657,-0.742398,0.662387,22.258065,430.549,...,0,0,0,0,0,0,0,0,0,0
1390,2513,C[C@H]1NCCCCCCNC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[...,-7.80,13.095577,13.095577,0.065481,-0.737917,0.561202,26.806452,430.549,...,0,0,0,0,0,0,0,0,0,0
1391,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.90,12.763992,12.763992,0.179945,-0.726122,0.611430,25.000000,388.512,...,0,0,0,0,0,0,0,0,0,0

In [5]:
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=True)

def calculate_mordred_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Return None if the SMILES is invalid
    return calc(mol)

In [6]:
print('start')
#2D Mordred train descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Train.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
train_mordred_2d = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_mordred_2d.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_Mordred_desc.csv', index=False)
print('Shape: ',train_mordred_2d.shape)
train_mordred_2d

start

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (5568, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,915,CC[C@H](C)[C@H](NC(=O)[C@@H]1CC(=O)N[C@@H](Cc2...,-7.0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,155.712529,2.416852,4.832818,...,11.593980,169.458441,1772.125588,6.420745,107741,214,630.0,725.0,55.173611,28.291667
1,888,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1cccc(Cl)c1)N(C)...,-7.0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,152.500384,2.445965,4.858291,...,11.590155,178.997365,1742.937365,6.835048,106182,208,620.0,719.0,49.861111,27.277778
2,593,C/N=C(\NC)NCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C...,-7.0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,3,154.777488,2.415089,4.830179,...,11.523579,167.253791,1732.084392,6.511595,102214,204,616.0,705.0,50.027778,28.083333
3,916,CC[C@H](C)[C@H](NC(=O)[C@@H](NC(=O)[C@@H]1CC(=...,-7.0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,149.378369,2.419912,4.839823,...,11.562315,165.286866,1724.125588,6.338697,101212,208,608.0,699.0,55.673611,27.319444
4,900,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O...,-7.0,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,150.261697,2.429936,4.859872,...,11.591302,165.339859,1722.146324,6.285206,107844,215,608.0,706.0,56.194444,27.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.7,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,35.896500,2.304816,4.609632,...,9.859065,63.474076,402.263091,6.385128,2286,42,138.0,153.0,10.638889,6.583333
5564,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.6,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,33.357653,2.311467,4.622934,...,9.832367,61.242657,374.231791,6.565470,1880,40,130.0,145.0,10.138889,6.083333
5565,2512,CC(C)C[C@H]1NC(=O)[C@@H](C)NCCCCCCNC(=O)[C@H](...,-5.5,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,31.502840,2.295993,4.591987,...,9.633842,59.559229,370.258006,6.170967,1648,37,118.0,129.0,10.777778,6.083333
5566,2511,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)[C@@H](C)NCC...,-6.3,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,30.506102,2.303541,4.607082,...,9.648660,58.482085,356.242356,6.249866,1472,37,114.0,126.0,10.527778,5.861111
5567,2506,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)CNCCCCCCNC1=O,-7.8,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,29.221909,2.295553,4.591106,...,9.537411,57.097912,342.226705,6.337532,1337,34,108.0,118.0,9.666667,5.666667

In [7]:
#2D Mordred test descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Test.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
test_mordred_2d = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_mordred_2d.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_Mordred_desc.csv', index=False)
print('Shape: ',test_mordred_2d.shape)
test_mordred_2d

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (1392, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,908,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-7.00,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,155.498239,2.424408,4.847496,...,11.617204,168.482860,1776.076051,6.529691,111779,220,626.0,728.0,55.444444,28.277778
1,923,CC[C@H](C)[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](...,-7.00,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,150.138684,2.427131,4.854261,...,11.589822,165.351205,1724.125588,6.338697,99910,213,610.0,706.0,56.284722,27.402778
2,897,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.00,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,150.676716,2.420176,4.840351,...,11.578086,164.308833,1700.068073,6.464137,103927,212,606.0,704.0,53.222222,27.333333
3,587,CC(C)C[C@@H]1NC(=O)[C@H](Cc2c[nH]cn2)NC(=O)[C@...,-6.74,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,151.698924,2.415398,4.830623,...,11.527095,177.329996,1685.010893,6.633901,95572,199,610.0,701.0,47.777778,27.083333
4,921,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.54,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,145.614560,2.422204,4.844100,...,11.547955,161.156358,1668.062988,6.415627,93670,207,588.0,682.0,53.972222,26.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,2481,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccccc...,-4.50,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.436032,2.302525,4.605049,...,9.885069,65.694305,430.294391,6.236151,2750,44,146.0,161.0,11.138889,7.083333
1388,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-4.80,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.436032,2.302525,4.605049,...,9.885069,65.694305,430.294391,6.236151,2750,44,146.0,161.0,11.138889,7.083333
1389,5604,CC(C)CN1CC(=O)N[C@@H](Cc2ccccc2)C(=O)NCCCCC(=O...,-6.38,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,37.855097,2.317338,4.629714,...,9.940542,65.841858,430.258006,6.619354,2644,45,148.0,164.0,11.750000,7.000000
1390,2513,C[C@H]1NCCCCCCNC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[...,-7.80,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,39.745462,2.403441,4.738314,...,10.079414,79.819128,430.258006,6.619354,2650,47,154.0,176.0,10.250000,6.972222
1391,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.90,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,34.487329,2.307278,4.602399,...,9.845805,62.359842,388.247441,6.470791,2069,41,134.0,149.0,10.388889,6.333333

In [8]:
#RDKit 3d descriptors
def generate_3d_descriptors(smiles):
    # Convert SMILES to a molecule object
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    
    # Add hydrogens
    mol = Chem.AddHs(mol)
    
    # Generate 3D coordinates for the molecule
    AllChem.EmbedMolecule(mol)
    
    try:
        descriptors = Descriptors3D.CalcMolDescriptors3D(mol)
        return descriptors
    except Exception as e:
        print(f"Error calculating descriptors for SMILES '{smiles}': {e}")
        return None

In [9]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Train.csv")
descriptor_data = []
for smiles in tqdm(df_train['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors =generate_3d_descriptors(smiles) 
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

3d_descriptors:   0%|          | 2/5568 [00:04<2:50:39,  1.84s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](Cc1cccc(Cl)c1)N(C)C(=O)[C@H](CC(C)C)NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H]1CC(=O)N[C@@H](Cc2ccccc2)C(=O)N(C)[C@@H](Cc2ccccc2)C(=O)N2CCC[C@H]2C(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C)C)C(=O)N1)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   0%|          | 5/5568 [00:23<6:55:51,  4.49s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@@H](NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H]1CC(=O)N(C)[C@@H](C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](Cc2ccccc2)C(=O)N[C@@H]([C@@H](C)O)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N(C)[C@@H](CC(C)C)C(=O)N1)C(C)C)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   0%|          | 9/5568 [00:35<4:36:16,  2.98s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](C)N(C)C(=O)[C@@H]1CC(=O)N[C@@H](C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@@H](C(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](Cc2ccccc2)C(=O)N1)C(C)C)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   0%|          | 16/5568 [01:00<5:11:35,  3.37s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@@H]1CC(=O)N(C)CCC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N1)[C@@H](C)CC)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   0%|          | 27/5568 [01:35<3:34:30,  2.32s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@@H]1CCCN1C(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H]1CC(=O)N[C@@H](Cc2ccccc2)C(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N(C)[C@@H](C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N1)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   1%|          | 29/5568 [01:43<4:47:20,  3.11s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)CN(C)C(=O)[C@H](C)N(C)C(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@@H]1CC(=O)N[C@H](C(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](Cc2ccccc2)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N1)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   1%|          | 60/5568 [03:31<4:24:46,  2.88s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](C)N(C)C(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H]1CC(=O)N[C@H](C)C(=O)N[C@@H](C(C)C)C(=O)N(C)[C@@H](Cc2ccccc2)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](Cc2ccccc2)C(=O)N1)C(C)C)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   2%|▏         | 128/5568 [06:38<3:16:40,  2.17s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@@H]1NC(=O)[C@H](C(C)C)NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@H](C(C)C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C)NC(=O)C[C@@H](C(=O)N(C)[C@@H](Cc2ccccc2)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@H](C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@H](C(=O)N2CCCCC2)[C@@H](C)CC)[C@@H](C)O)NC1=O': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   3%|▎         | 147/5568 [07:19<2:18:22,  1.53s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)CN(C)C(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@@H]1CC(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@@H]([C@@H](C)O)C(=O)N1)C(C)C)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   4%|▎         | 197/5568 [09:23<1:54:44,  1.28s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@@H]1CC(=O)N(C)[C@@H](C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N1)C(C)C)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors: 100%|██████████| 5568/5568 [1:07:31<00:00,  1.37smiles/s]

In [10]:
descriptor_df = pd.DataFrame(descriptor_data)
descriptor_df

,PMI1,PMI2,PMI3,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF
0,55956.786985,99960.858242,143887.632605,0.388892,0.694715,9.194126,0.000012,0.921283,0.258063,0.139264,1.710681
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,58796.959784,81694.256927,121554.991217,0.483707,0.672077,8.694432,0.000011,0.875230,0.176260,0.265588,2.215455
3,67853.021592,84551.096230,143909.838389,0.471497,0.587528,9.266829,0.000009,0.881868,0.218376,0.114802,1.520740
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5563,1743.977405,5966.057232,7181.572782,0.242841,0.830745,4.300825,0.000476,0.970066,0.440755,0.160409,0.914105
5564,1098.802374,5640.564299,6362.780182,0.172692,0.886494,4.182530,0.000807,0.984976,0.569228,0.113515,0.738746
5565,2206.160044,3101.366929,4907.135825,0.449582,0.632012,3.712842,0.000286,0.893239,0.217702,0.164155,0.804438
5566,2030.228104,2614.705158,4174.247246,0.486370,0.626390,3.517138,0.000309,0.873753,0.189529,0.230433,0.936180
5567,2393.700752,2435.731809,4182.051056,0.572375,0.582425,3.627362,0.000243,0.819992,0.153918,0.248385,0.937849

In [11]:
num_columns = descriptor_df.shape[1]
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
train_3d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , train_3d_rdkit.shape)
train_3d_rdkit.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_3d_RDKit_desc.csv',index=False)
print('Shape after: ',train_3d_rdkit.shape)
train_3d_rdkit

Shape before: (5568, 14)
Shape after:  (5568, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,915,CC[C@H](C)[C@H](NC(=O)[C@@H]1CC(=O)N[C@@H](Cc2...,-7.0,55956.786985,99960.858242,143887.632605,0.388892,0.694715,9.194126,0.000012,0.921283,0.258063,0.139264,1.710681
1,888,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1cccc(Cl)c1)N(C)...,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,593,C/N=C(\NC)NCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C...,-7.0,58796.959784,81694.256927,121554.991217,0.483707,0.672077,8.694432,0.000011,0.875230,0.176260,0.265588,2.215455
3,916,CC[C@H](C)[C@H](NC(=O)[C@@H](NC(=O)[C@@H]1CC(=...,-7.0,67853.021592,84551.096230,143909.838389,0.471497,0.587528,9.266829,0.000009,0.881868,0.218376,0.114802,1.520740
4,900,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccccc1)N(C)C(=O...,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.7,1743.977405,5966.057232,7181.572782,0.242841,0.830745,4.300825,0.000476,0.970066,0.440755,0.160409,0.914105
5564,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.6,1098.802374,5640.564299,6362.780182,0.172692,0.886494,4.182530,0.000807,0.984976,0.569228,0.113515,0.738746
5565,2512,CC(C)C[C@H]1NC(=O)[C@@H](C)NCCCCCCNC(=O)[C@H](...,-5.5,2206.160044,3101.366929,4907.135825,0.449582,0.632012,3.712842,0.000286,0.893239,0.217702,0.164155,0.804438
5566,2511,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)[C@@H](C)NCC...,-6.3,2030.228104,2614.705158,4174.247246,0.486370,0.626390,3.517138,0.000309,0.873753,0.189529,0.230433,0.936180
5567,2506,CC(C)[C@@H]1NC(=O)[C@@H](CO)NC(=O)CNCCCCCCNC1=O,-7.8,2393.700752,2435.731809,4182.051056,0.572375,0.582425,3.627362,0.000243,0.819992,0.153918,0.248385,0.937849

In [12]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/PAMPA/data/Test.csv")
descriptor_data = []
for smiles in tqdm(df_test['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors = generate_3d_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

descriptor_data

3d_descriptors:   0%|          | 3/1392 [00:14<1:46:39,  4.61s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](C)N(C)C(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](C(C)C)NC(=O)[C@@H](C(C)C)NC(=O)C[C@@H](C(=O)N(C)[C@@H](Cc2ccccc2)C(=O)N[C@H](C(=O)N(C)[C@@H](C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@H](C(=O)N2CCCCC2)[C@@H](C)CC)C(C)C)NC1=O': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors:   1%|          | 8/1392 [00:30<1:12:46,  3.16s/smiles]

Error calculating descriptors for SMILES 'CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@@H]1CCCN1C(=O)[C@@H]1CC(=O)N(C)CCC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)O)C(=O)N(C)[C@@H](C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N1)[C@@H](C)CC)C(=O)N1CCCCC1': Computing 3D Descriptors requires a structure with at least 1 conformer

3d_descriptors: 100%|██████████| 1392/1392 [17:09<00:00,  1.35smiles/s]

[{'PMI1': 33760.20801631492,
  'PMI2': 138153.24748316398,
  'PMI3': 155908.19028809635,
  'NPR1': 0.21653902821866394,
  'NPR2': 0.8861192425354708,
  'RadiusOfGyration': 9.602165886296683,
  'InertialShapeFactor': 2.624744616820032e-05,
  'Eccentricity': 0.9762739621940743,
  'Asphericity': 0.4863496070256628,
  'SpherocityIndex': 0.16577438314214743,
  'PBF': 1.9354371692180525},
 {'PMI1': 56404.75574202478,
  'PMI2': 90641.86511948316,
  'PMI3': 134352.71668506993,
  'NPR1': 0.41982594125164285,
  'NPR2': 0.6746559902614595,
  'RadiusOfGyration': 9.030600241149411,
  'InertialShapeFactor': 1.1960977073406631e-05,
  'Eccentricity': 0.9076046380733035,
  'Asphericity': 0.2313224702984822,
  'SpherocityIndex': 0.1663458105940371,
  'PBF': 1.8338161502063013},
 {'PMI1': nan,
  'PMI2': nan,
  'PMI3': nan,
  'NPR1': nan,
  'NPR2': nan,
  'RadiusOfGyration': nan,
  'InertialShapeFactor': nan,
  'Eccentricity': nan,
  'Asphericity': nan,
  'SpherocityIndex': nan,
  'PBF': nan},
 {'PMI1': 48070.001754414334,
  'PMI2': 80006.49765601511,
  'PMI3': 115096.00223571503,
  'NPR1': 0.41765135904518763,
  'NPR2': 0.6951283806727092,
  'RadiusOfGyration': 8.491649686522928,
  'InertialShapeFactor': 1.4460752138601174e-05,
  'Eccentricity': 0.9086073642050826,
  'Asphericity': 0.2280862859980416,
  'SpherocityIndex': 0.18606050092001905,
  'PBF': 1.797710198028821},
 {'PMI1': 65151.35559169309,
  'PMI2': 73494.98536710227,
  'PMI3': 128961.9006754993,
  'NPR1': 0.5051984752894605,
  'NPR2': 0.569896884135061,
  'RadiusOfGyration': 8.95331921621764,
  'InertialShapeFactor': 8.747275923261432e-06,
  'Eccentricity': 0.8630031868800975,
  'Asphericity': 0.20157967105415417,
  'SpherocityIndex': 0.13561528534805156,
  'PBF': 1.6511145872049207},
 {'PMI1': 42978.47477335339,
  'PMI2': 90143.69843207409,
  'PMI3': 112086.12885740402,
  'NPR1': 0.3834415124464741,
  'NPR2': 0.8042359866558948,
  'RadiusOfGyration': 8.583325249434429,
  'InertialShapeFactor': 1.8712529723239977e-05,
  'Eccentricity': 0.9235651609565838,
  'Asphericity': 0.24886931217792047,
  'SpherocityIndex': 0.2766921911774617,
  'PBF': 2.0833362363615398},
 {'PMI1': 45035.3373744521,
  'PMI2': 95101.07669609973,
  'PMI3': 128844.75160649199,
  'NPR1': 0.34953179553634955,
  'NPR2': 0.7381059415330344,
  'RadiusOfGyration': 9.027905188148319,
  'InertialShapeFactor': 1.638948400443762e-05,
  'Eccentricity': 0.9369245027797788,
  'Asphericity': 0.29493030655987484,
  'SpherocityIndex': 0.1603294307950171,
  'PBF': 1.8005692649857796},
 {'PMI1': nan,
  'PMI2': nan,
  'PMI3': nan,
  'NPR1': nan,
  'NPR2': nan,
  'RadiusOfGyration': nan,
  'InertialShapeFactor': nan,
  'Eccentricity': nan,
  'Asphericity': nan,
  'SpherocityIndex': nan,
  'PBF': nan},
 {'PMI1': 49346.27829641066,
  'PMI2': 77458.86772273312,
  'PMI3': 112509.47829026091,
  'NPR1': 0.43859663244640773,
  'NPR2': 0.688465264436642,
  'RadiusOfGyration': 8.65035332859775,
  'InertialShapeFactor': 1.3951716080819807e-05,
  'Eccentricity': 0.8986840345787115,
  'Asphericity': 0.20982352234745347,
  'SpherocityIndex': 0.22002410231120917,
  'PBF': 1.9940260926716895},
 {'PMI1': 25514.095605926614,
  'PMI2': 101309.4487640631,
  'PMI3': 119010.71663205528,
  'NPR1': 0.21438485817044856,
  'NPR2': 0.851263244446136,
  'RadiusOfGyration': 8.7813075384209,
  'InertialShapeFactor': 3.336442951355869e-05,
  'Eccentricity': 0.97674926802493,
  'Asphericity': 0.48978290661333407,
  'SpherocityIndex': 0.10822423865855278,
  'PBF': 1.4164867830259205},
 {'PMI1': 52801.08397879579,
  'PMI2': 70115.64246583279,
  'PMI3': 115278.95629629353,
  'NPR1': 0.45802881701222914,
  'NPR2': 0.6082258611504029,
  'RadiusOfGyration': 8.67361696861169,
  'InertialShapeFactor': 1.1519192700563842e-05,
  'Eccentricity': 0.8889373446910518,
  'Asphericity': 0.22006744151031887,
  'SpherocityIndex': 0.12518588251863066,
  'PBF': 1.4869407836636033},
 {'PMI1': 32073.906880531842,
  'PMI2': 103382.62175235628,
  'PMI3': 126378.99789142291,
  'NPR1': 0.2537914322448401,
  'NPR2': 0.8180364101413139,
  'RadiusOfGyration': 9.102728079742805,
  'InertialShapeFactor': 2.550473234172305e-05,
  'Eccentricity': 0.9672589668331397,
  'Asphericity': 0.42321099085038627,
  'SpherocityIndex': 0.12111128248427769,
  'PBF': 1.5802220383914736},
 {'PMI1': 31539.864299003326,
  'PMI2': 103379.35731871644,
  'PMI3': 122669.61716319787,
  'NPR1': 0.2571122746477895,
  'NPR2': 0.842746229338778,
  'RadiusOfGyration': 9.04569378931137,
  'InertialShapeFactor': 2.6720033458273602e-05,
  'Eccentricity': 0.9663815386406343,
  'Asphericity': 0.4170984049328508,
  'SpherocityIndex': 0.17545755546527517,
  'PBF': 1.846257482431642},
 {'PMI1': 18575.32646565027,
  'PMI2': 154696.79451750827,
  'PMI3': 158873.18937015432,
  'NPR1': 0.11691920165568101,
  'NPR2': 0.9737124000015158,
  'RadiusOfGyration': 10.286852607649777,
  'InertialShapeFactor': 5.241966550639728e-05,
  'Eccentricity': 0.9931414301519186,
  'Asphericity': 0.6930712638656007,
  'SpherocityIndex': 0.14035156567366291,
  'PBF': 1.8781524431907712},
 {'PMI1': 34166.33969100182,
  'PMI2': 81922.12343167416,
  'PMI3': 108584.92020511968,
  'NPR1': 0.3146508707328857,
  'NPR2': 0.7544521216843111,
  'RadiusOfGyration': 8.485900962314087,
  'InertialShapeFactor': 2.208173683536275e-05,
  'Eccentricity': 0.9492074744475187,
  'Asphericity': 0.33795407545597345,
  'SpherocityIndex': 0.1386865400404166,
  'PBF': 1.5657242889077698},
 {'PMI1': 36264.98710439818,
  'PMI2': 74816.47449702599,
  'PMI3': 102973.94434624018,
  'NPR1': 0.35217634261401676,
  'NPR2': 0.7265573342074054,
  'RadiusOfGyration': 8.282953941081766,
  'InertialShapeFactor': 2.0034677859275714e-05,
  'Eccentricity': 0.9359336641573562,
  'Asphericity': 0.2937226911242158,
  'SpherocityIndex': 0.12848553980192515,
  'PBF': 1.4763407785351441},
 {'PMI1': 49744.71058097803,
  'PMI2': 61274.307395509466,
  'PMI3': 96345.7324404694,
  'NPR1': 0.5163146236053014,
  'NPR2': 0.6359836169533504,
  'RadiusOfGyration': 8.168103507697637,
  'InertialShapeFactor': 1.2784949586108262e-05,
  'Eccentricity': 0.8563989779602239,
  'Asphericity': 0.16439907959023037,
  'SpherocityIndex': 0.24263304000960698,
  'PBF': 2.0262292459313485},
 {'PMI1': 39212.863540497885,
  'PMI2': 75680.86083290089,
  'PMI3': 104778.78577740511,
  'NPR1': 0.3742443019315261,
  'NPR2': 0.7222918291273136,
  'RadiusOfGyration': 8.425976864519647,
  'InertialShapeFactor': 1.8419767492403402e-05,
  'Eccentricity': 0.9273301475050754,
  'Asphericity': 0.26838082929385026,
  'SpherocityIndex': 0.15963690549304677,
  'PBF': 1.6395140727782942},
 {'PMI1': 42700.104700992204,
  'PMI2': 67362.27113479501,
  'PMI3': 96263.40039392533,
  'NPR1': 0.44357569466958885,
  'NPR2': 0.6997703266156997,
  'RadiusOfGyration': 8.168837027665138,
  'InertialShapeFactor': 1.6388023671507286e-05,
  'Eccentricity': 0.8962369123721649,
  'Asphericity': 0.2026070637820902,
  'SpherocityIndex': 0.24100752080556617,
  'PBF': 2.03793488339765},
 {'PMI1': 38884.42508178769,
  'PMI2': 78605.88009951651,
  'PMI3': 108474.0177765027,
  'NPR1': 0.35846763933741477,
  'NPR2': 0.7246516881256689,
  'RadiusOfGyration': 8.554345295194434,
  'InertialShapeFactor': 1.8636039663733495e-05,
  'Eccentricity': 0.9335421530642637,
  'Asphericity': 0.2864327816180739,
  'SpherocityIndex': 0.16483249042921366,
  'PBF': 1.6941164400524076},
 {'PMI1': 34915.78239504987,
  'PMI2': 73979.54035884005,
  'PMI3': 98151.02952431455,
  'NPR1': 0.3557352639525837,
  'NPR2': 0.7537316798140503,
  'RadiusOfGyration': 8.220467155221455,
  'InertialShapeFactor': 2.1587134187229594e-05,
  'Eccentricity': 0.9345867653570672,
  'Asphericity': 0.2850101331733672,
  'SpherocityIndex': 0.1693792731029271,
  'PBF': 1.7084200027343557},
 {'PMI1': 30110.450325303056,
  'PMI2': 93566.96361025282,
  'PMI3': 115831.72425379012,
  'NPR1': 0.2599499447951783,
  'NPR2': 0.8077835689059185,
  'RadiusOfGyration': 8.84727849299503,
  'InertialShapeFactor': 2.6827349314902293e-05,
  'Eccentricity': 0.965622092850502,
  'Asphericity': 0.41386429276579756,
  'SpherocityIndex': 0.10671258455387066,
  'PBF': 1.4108819551294847},
 {'PMI1': 25626.062430927737,
  'PMI2': 98578.22536731137,
  'PMI3': 114540.53006415529,
  'NPR1': 0.22372921110609778,
  'NPR2': 0.8606405550253411,
  'RadiusOfGyration': 8.86802907254227,
  'InertialShapeFactor': 3.3584580438181015e-05,
  'Eccentricity': 0.9746513428389882,
  'Asphericity': 0.47308110577315104,
  'SpherocityIndex': 0.14713137281782884,
  'PBF': 1.6149652625624402},
 {'PMI1': 47838.22596423603,
  'PMI2': 64993.558083158445,
  'PMI3': 101704.54547112697,
  'NPR1': 0.4703646797951315,
  'NPR2': 0.6390428056296613,
  'RadiusOfGyration': 8.414618137417085,
  'InertialShapeFactor': 1.3358413543750791e-05,
  'Eccentricity': 0.8824721344049473,
  'Asphericity': 0.19743616715083812,
  'SpherocityIndex': 0.18338873189695848,
  'PBF': 1.7231139814197318},
 {'PMI1': 32657.322952562045,
  'PMI2': 90548.13858077381,
  'PMI3': 111723.27403124509,
  'NPR1': 0.29230545950013004,
  'NPR2': 0.8104680011028916,
  'RadiusOfGyration': 8.82033086934986,
  'InertialShapeFactor': 2.4817343487712563e-05,
  'Eccentricity': 0.9563250066512,
  'Asphericity': 0.36422838841801575,
  'SpherocityIndex': 0.16650193592205445,
  'PBF': 1.6671570790088728},
 {'PMI1': 37360.38001085014,
  'PMI2': 82418.68488735244,
  'PMI3': 109012.28732814186,
  'NPR1': 0.34271714617261717,
  'NPR2': 0.756049495955084,
  'RadiusOfGyration': 8.715636234269482,
  'InertialShapeFactor': 2.0236665037548154e-05,
  'Eccentricity': 0.9394386396775987,
  'Asphericity': 0.3007505489384603,
  'SpherocityIndex': 0.16949595844493248,
  'PBF': 1.7784957516477036},
 {'PMI1': 30234.013754839285,
  'PMI2': 82790.81996871384,
  'PMI3': 105510.16447977873,
  'NPR1': 0.2865507214770166,
  'NPR2': 0.7846715089197013,
  'RadiusOfGyration': 8.523865719584881,
  'InertialShapeFactor': 2.5953269561971605e-05,
  'Eccentricity': 0.9580650729574695,
  'Asphericity': 0.3745956907968565,
  'SpherocityIndex': 0.12349959015249681,
  'PBF': 1.4368400297028106},
 {'PMI1': 40511.878710340956,
  'PMI2': 65397.15973378773,
  'PMI3': 96936.32539547727,
  'NPR1': 0.4179225748970995,
  'NPR2': 0.6746403834370944,
  'RadiusOfGyration': 8.21476208309282,
  'InertialShapeFactor': 1.6652902924121548e-05,
  'Eccentricity': 0.9084826478207375,
  'Asphericity': 0.2332030424054411,
  'SpherocityIndex': 0.16885984165587,
  'PBF': 1.668452554944534},
 {'PMI1': 59732.109631572486,
  'PMI2': 67829.86634401244,
  'PMI3': 119986.82661694582,
  'NPR1': 0.49782223028754125,
  'NPR2': 0.5653109450136319,
  'RadiusOfGyration': 9.081013681837607,
  'InertialShapeFactor': 9.464104792220941e-06,
  'Eccentricity': 0.8672790940819098,
  'Asphericity': 0.2094161289962417,
  'SpherocityIndex': 0.11695176312711328,
  'PBF': 1.5397411026919838},
 {'PMI1': 34536.6479613273,
  'PMI2': 86479.22948237354,
  'PMI3': 112504.72908497915,
  'NPR1': 0.30697952203627316,
  'NPR2': 0.7686719499324554,
  'RadiusOfGyration': 8.852655525079719,
  'InertialShapeFactor': 2.2256703974085214e-05,
  'Eccentricity': 0.9517161199908202,
  'Asphericity': 0.3467469368590783,
  'SpherocityIndex': 0.13159070563504996,
  'PBF': 1.5783155188274645},
 {'PMI1': 36931.53857423906,
  'PMI2': 69893.83798099312,
  'PMI3': 95508.78021306898,
  'NPR1': 0.3866821300811202,
  'NPR2': 0.7318053672664241,
  'RadiusOfGyration': 8.242960012472142,
  'InertialShapeFactor': 1.981518765581248e-05,
  'Eccentricity': 0.9222130612152095,
  'Asphericity': 0.25276228818750884,
  'SpherocityIndex': 0.1855679991140888,
  'PBF': 1.7259234236541143},
 {'PMI1': 38705.79960061331,
  'PMI2': 61403.35277999679,
  'PMI3': 90552.67505571767,
  'NPR1': 0.4274396043716806,
  'NPR2': 0.6780954040531094,
  'RadiusOfGyration': 8.012412543778732,
  'InertialShapeFactor': 1.7519219627292355e-05,
  'Eccentricity': 0.9040439063533259,
  'Asphericity': 0.22298459155973505,
  'SpherocityIndex': 0.1978686303672227,
  'PBF': 1.7760919908250565},
 {'PMI1': 35216.50788931466,
  'PMI2': 71348.49598467864,
  'PMI3': 100386.40721490998,
  'NPR1': 0.3508095255757305,
  'NPR2': 0.7107386145609715,
  'RadiusOfGyration': 8.35599785570488,
  'InertialShapeFactor': 2.0181973090427368e-05,
  'Eccentricity': 0.936446836059224,
  'Asphericity': 0.2986692928721235,
  'SpherocityIndex': 0.11110710884172784,
  'PBF': 1.3516420171913583},
 {'PMI1': 39153.97953089331,
  'PMI2': 65506.544866406795,
  'PMI3': 89859.33415989956,
  'NPR1': 0.43572523541317404,
  'NPR2': 0.728989875997096,
  'RadiusOfGyration': 8.117962521823108,
  'InertialShapeFactor': 1.8618538517187193e-05,
  'Eccentricity': 0.9000797293707563,
  'Asphericity': 0.20395113618742153,
  'SpherocityIndex': 0.2735686107714549,
  'PBF': 2.0516691688107445},
 {'PMI1': 28054.60458498268,
  'PMI2': 81542.16521785635,
  'PMI3': 97883.80316437293,
  'NPR1': 0.28661130522147305,
  'NPR2': 0.8330506435362486,
  'RadiusOfGyration': 8.38673128319181,
  'InertialShapeFactor': 2.9693900728943843e-05,
  'Eccentricity': 0.9580469506862613,
  'Asphericity': 0.37186630099011875,
  'SpherocityIndex': 0.1925207989814334,
  'PBF': 1.784138794869462},
 {'PMI1': 33087.97870029736,
  'PMI2': 71988.79323212584,
  'PMI3': 98911.67608036184,
  'NPR1': 0.33452045311025447,
  'NPR2': 0.7278088501264278,
  'RadiusOfGyration': 8.330038265848321,
  'InertialShapeFactor': 2.1996171380510678e-05,
  'Eccentricity': 0.9423884901944155,
  'Asphericity': 0.315821721212032,
  'SpherocityIndex': 0.11325161897278989,
  'PBF': 1.3946363261596915},
 {'PMI1': 35777.272067479564,
  'PMI2': 68303.15941481167,
  'PMI3': 96456.4316758991,
  'NPR1': 0.3709163966141097,
  'NPR2': 0.7081244685094245,
  'RadiusOfGyration': 8.282012923482503,
  'InertialShapeFactor': 1.9792578572615317e-05,
  'Eccentricity': 0.9286662622938364,
  'Asphericity': 0.27514588540829904,
  'SpherocityIndex': 0.1394502354016438,
  'PBF': 1.5465510858700524},
 {'PMI1': 40249.089672499016,
  'PMI2': 76938.63231654777,
  'PMI3': 112238.801588466,
  'NPR1': 0.3586022757092155,
  'NPR2': 0.6854905008577196,
  'RadiusOfGyration': 8.864234653108632,
  'InertialShapeFactor': 1.7031205088995947e-05,
  'Eccentricity': 0.9334904433662788,
  'Asphericity': 0.2954124503659245,
  'SpherocityIndex': 0.0939693114434754,
  'PBF': 1.3294018530864067},
 {'PMI1': 44898.400227207996,
  'PMI2': 60447.878934469096,
  'PMI3': 97266.85122281172,
  'NPR1': 0.4616002231259451,
  'NPR2': 0.6214643341954142,
  'RadiusOfGyration': 8.347589537563275,
  'InertialShapeFactor': 1.3841569656168123e-05,
  'Eccentricity': 0.8870880644051512,
  'Asphericity': 0.21143277535473104,
  'SpherocityIndex': 0.1526140681749315,
  'PBF': 1.638324925660353},
 {'PMI1': 32513.092168436142,
  'PMI2': 53352.676608616406,
  'PMI3': 73225.98397724007,
  'NPR1': 0.44401031440617833,
  'NPR2': 0.7286030683479701,
  'RadiusOfGyration': 7.406977214658587,
  'InertialShapeFactor': 2.2409528585389402e-05,
  'Eccentricity': 0.8960216742361352,
  'Asphericity': 0.19650398499955232,
  'SpherocityIndex': 0.2852208490344108,
  'PBF': 1.91880446442281},
 {'PMI1': 34231.369910772024,
  'PMI2': 76553.5635583605,
  'PMI3': 102631.07610907141,
  'NPR1': 0.3335380589246921,
  'NPR2': 0.7459101712721304,
  'RadiusOfGyration': 8.587663909284515,
  'InertialShapeFactor': 2.1790251842576866e-05,
  'Eccentricity': 0.9427366351472443,
  'Asphericity': 0.3139534900750943,
  'SpherocityIndex': 0.16084389475952476,
  'PBF': 1.6524103550452724},
 {'PMI1': 37823.19291048206,
  'PMI2': 71111.59776101548,
  'PMI3': 94814.75186852865,
  'NPR1': 0.3989167525632318,
  'NPR2': 0.7500056305544072,
  'RadiusOfGyration': 8.393907798633972,
  'InertialShapeFactor': 1.9829252182106384e-05,
  'Eccentricity': 0.9169871452340025,
  'Asphericity': 0.2369325954774446,
  'SpherocityIndex': 0.22250019763231718,
  'PBF': 1.9348568576433909},
 {'PMI1': 38193.04072090783,
  'PMI2': 55605.575656879424,
  'PMI3': 85152.90990980783,
  'NPR1': 0.44852302477227257,
  'NPR2': 0.6530085198001534,
  'RadiusOfGyration': 7.877645436421362,
  'InertialShapeFactor': 1.709757870738687e-05,
  'Eccentricity': 0.8937712773686182,
  'Asphericity': 0.21118584417796601,
  'SpherocityIndex': 0.17423164954695078,
  'PBF': 1.618629047082473},
 {'PMI1': 26660.839081405236,
  'PMI2': 88145.18406976754,
  'PMI3': 108515.5315937143,
  'NPR1': 0.2456868495214518,
  'NPR2': 0.8122817330867068,
  'RadiusOfGyration': 8.82494367267063,
  'InertialShapeFactor': 3.0467223128518772e-05,
  'Eccentricity': 0.9693492518036125,
  'Asphericity': 0.43693268835358884,
  'SpherocityIndex': 0.1071441890284147,
  'PBF': 1.4174275890633583},
 {'PMI1': 32207.20644479432,
  'PMI2': 83730.89920924898,
  'PMI3': 105829.20891678569,
  'NPR1': 0.30433192097390704,
  'NPR2': 0.7911889360817883,
  'RadiusOfGyration': 8.79418078862836,
  'InertialShapeFactor': 2.4565587128394642e-05,
  'Eccentricity': 0.9525660511882268,
  'Asphericity': 0.3482349041721904,
  'SpherocityIndex': 0.16605725533091364,
  'PBF': 1.7249113570033514},
 {'PMI1': 27071.893126189072,
  'PMI2': 69232.02600039124,
  'PMI3': 87455.56466502574,
  'NPR1': 0.3095502639526763,
  'NPR2': 0.7916251671985115,
  'RadiusOfGyration': 8.007824018416676,
  'InertialShapeFactor': 2.9241588813480554e-05,
  'Eccentricity': 0.9508830811865507,
  'Asphericity': 0.34090494067404176,
  'SpherocityIndex': 0.18065197299010566,
  'PBF': 1.6838089686580966},
 {'PMI1': 32800.27853652152,
  'PMI2': 64927.20165668508,
  'PMI3': 88667.48467647801,
  'NPR1': 0.3699245406159906,
  'NPR2': 0.7322549172741919,
  'RadiusOfGyration': 8.070486677229026,
  'InertialShapeFactor': 2.2324655458607206e-05,
  'Eccentricity': 0.9290618032456442,
  'Asphericity': 0.2715294413327425,
  'SpherocityIndex': 0.16738959906459913,
  'PBF': 1.612446803908516},
 {'PMI1': 36562.91553283476,
  'PMI2': 46672.856785166085,
  'PMI3': 72724.1141363672,
  'NPR1': 0.5027619238410319,
  'NPR2': 0.6417796536874741,
  'RadiusOfGyration': 7.390014625344716,
  'InertialShapeFactor': 1.75527483061665e-05,
  'Eccentricity': 0.8644249232499399,
  'Asphericity': 0.17172794972292937,
  'SpherocityIndex': 0.23976359126873623,
  'PBF': 1.8062896843373164},
 {'PMI1': 25438.091880549735,
  'PMI2': 79054.90445528242,
  'PMI3': 92363.52102103508,
  'NPR1': 0.2754127560247125,
  'NPR2': 0.8559104674807523,
  'RadiusOfGyration': 8.329153034002909,
  'InertialShapeFactor': 3.364680305031808e-05,
  'Eccentricity': 0.9613260704978682,
  'Asphericity': 0.38866639212660625,
  'SpherocityIndex': 0.23744185510352658,
  'PBF': 1.9383516837694172},
 {'PMI1': 28518.041524723125,
  'PMI2': 81985.3235450023,
  'PMI3': 96870.32003698545,
  'NPR1': 0.294394005448055,
  'NPR2': 0.8463410001505106,
  'RadiusOfGyration': 8.548752926804765,
  'InertialShapeFactor': 2.967738858984383e-05,
  'Eccentricity': 0.9556841369177634,
  'Asphericity': 0.36054205364627834,
  'SpherocityIndex': 0.2372373137032603,
  'PBF': 1.9645003814492605},
 {'PMI1': 31694.73044536348,
  'PMI2': 45943.280394711095,
  'PMI3': 63161.31904917107,
  'NPR1': 0.5018060249927513,
  'NPR2': 0.7273958347662794,
  'RadiusOfGyration': 7.056394618494354,
  'InertialShapeFactor': 2.295005587822211e-05,
  'Eccentricity': 0.8649801808602173,
  'Asphericity': 0.15028191265325394,
  'SpherocityIndex': 0.3478547755605431,
  'PBF': 2.0629464603170775},
 {'PMI1': 37007.91021622114,
  'PMI2': 60548.91853130812,
  'PMI3': 90277.75603542903,
  'NPR1': 0.40993387343054455,
  'NPR2': 0.670695874491453,
  'RadiusOfGyration': 8.153203622703765,
  'InertialShapeFactor': 1.8123041008607845e-05,
  'Eccentricity': 0.9121152445904137,
  'Asphericity': 0.24237173497508896,
  'SpherocityIndex': 0.13840779091601743,
  'PBF': 1.4569039230594103},
 {'PMI1': 36008.42289637283,
  'PMI2': 47185.65863175447,
  'PMI3': 72910.51579776431,
  'NPR1': 0.4938714601368514,
  'NPR2': 0.6471721961566668,
  'RadiusOfGyration': 7.432845723173609,
  'InertialShapeFactor': 1.797280036449075e-05,
  'Eccentricity': 0.869534922163736,
  'Asphericity': 0.1763301413267525,

In [13]:
descriptor_df = pd.DataFrame(descriptor_data)

In [14]:
num_columns = descriptor_df.shape[1]
print('num_columns',num_columns)
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
print('descriptor_df.columns',descriptor_df.columns)
test_3d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , test_3d_rdkit.shape)
test_3d_rdkit.to_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_3d_RDKit_desc.csv',index=False)
print('Shape after: ',test_3d_rdkit.shape)
test_3d_rdkit

num_columns 11
descriptor_df.columns Index(['3d_rdkit_1', '3d_rdkit_2', '3d_rdkit_3', '3d_rdkit_4', '3d_rdkit_5',
       '3d_rdkit_6', '3d_rdkit_7', '3d_rdkit_8', '3d_rdkit_9', '3d_rdkit_10',
       '3d_rdkit_11'],
      dtype='object')
Shape before: (1392, 14)
Shape after:  (1392, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,908,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-7.00,33760.208016,138153.247483,155908.190288,0.216539,0.886119,9.602166,0.000026,0.976274,0.486350,0.165774,1.935437
1,923,CC[C@H](C)[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](...,-7.00,56404.755742,90641.865119,134352.716685,0.419826,0.674656,9.030600,0.000012,0.907605,0.231322,0.166346,1.833816
2,897,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,587,CC(C)C[C@@H]1NC(=O)[C@H](Cc2c[nH]cn2)NC(=O)[C@...,-6.74,48070.001754,80006.497656,115096.002236,0.417651,0.695128,8.491650,0.000014,0.908607,0.228086,0.186061,1.797710
4,921,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.54,65151.355592,73494.985367,128961.900675,0.505198,0.569897,8.953319,0.000009,0.863003,0.201580,0.135615,1.651115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,2481,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccccc...,-4.50,2415.488872,5133.998799,6699.482959,0.360549,0.766328,4.067647,0.000317,0.932740,0.277725,0.242032,1.069371
1388,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-4.80,2626.126299,7156.499036,7502.735704,0.350022,0.953852,4.480131,0.000363,0.936741,0.297375,0.448551,1.426593
1389,5604,CC(C)CN1CC(=O)N[C@@H](Cc2ccccc2)C(=O)NCCCCC(=O...,-6.38,2992.608278,4917.452764,5722.031906,0.522997,0.859389,3.978826,0.000287,0.852334,0.127018,0.491961,1.487795
1390,2513,C[C@H]1NCCCCCCNC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[...,-7.80,2522.551028,5008.984905,7154.625746,0.352576,0.700104,4.129789,0.000278,0.935783,0.298978,0.125983,0.754687
1391,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.90,993.283516,6491.648620,6960.719287,0.142698,0.932612,4.311728,0.000939,0.989766,0.633154,0.135854,0.858932

In [16]:
import os

#Train MOL structure generator
input_file = '/home/users/akshay/PCPpred/PAMPA/data/Train.smi'
output_dir = '/home/users/akshay/PCPpred/PAMPA/data/Train_mol'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 5568/5568 [1:09:23<00:00,  1.34it/s]

3D conformations generated and saved.

In [17]:
directory_path = '/home/users/akshay/PCPpred/PAMPA/data/Train_mol'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 5568

In [18]:
#Test MOL structure generator
input_file = '/home/users/akshay/PCPpred/PAMPA/data/Test.smi'
output_dir = '/home/users/akshay/PCPpred/PAMPA/data/Test_mol'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 1392/1392 [17:17<00:00,  1.34it/s]

3D conformations generated and saved.

In [19]:
directory_path = '/home/users/akshay/PCPpred/PAMPA/data/Test_mol'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 1392